### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by Awais-cb** [Stichoza/google-translate-php#102]
> Message: Server error: `POST http://translate.google.cn/translate_a/single?client=t&hl=en&dt=t&sl=en&tl=zh-CHS&ie=UTF-8&oe=UTF-8&multires=1&otf=0&pc=1&trs=1&ssel=0&tsel=0&kc=1&tk=790557.664419` resulted in a `503 Service Unavailable` response: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"> <html> <head><meta http-equiv="content-type" content="te (truncated...) Message: Server error: `POST http://translate.google.cn/translate_a/single?client=t&hl=en&dt=t&sl=en&tl=zh-CHS&ie=UTF-8&oe=UTF-8&multires=1&otf=0&pc=1&trs=1&ssel=0&tsel=0&kc=1&tk=790557.664419` resulted in a `503 Service Unavailable` response: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"> <html> <head><meta http-equiv="content-type" content="te (truncated...)

This is what i get when ever i hit google translator api using this library.I thought it was due to ip but i changed the ip ran it again but still this message comes up.Any help regarding this issue will be really appreciated.

**Comment by Stichoza** [comment]
You can see #62 #66 #67 #98  issues.

**Comment by sonamnrt** [comment]
sam problem i have faced
