### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by ozgurkaracam** [Stichoza/google-translate-php#104]
Fatal error: Uncaught Error: Class 'Stichoza\GoogleTranslate\GoogleTranslate' not found in ....

**Comment by MHuzaifaUmair** [comment]
Same Problem

**Comment by frzsombor** [comment]
Are you sure you are using this project properly with composer?
Have you included the `vendor/autoload.php` file before you tried using this package?
Please refer to the basic usage guide of composer: https://getcomposer.org/doc/01-basic-usage.md

**Comment by saeed74** [comment]
same problem
also included `vendor/autoload.php`  before use.

**Comment by saeed74** [comment]
i found solution.

Don't use `GoogleTranslate`class but use `TranslateClient` class

like this:

```
use Stichoza\GoogleTranslate\TranslateClient;

$tr = new TranslateClient();
...
```

**Comment by frzsombor** [comment]
If you can see a `src/Stichoza/GoogleTranslate/TranslateClient.php` file, and you can use `TranslateClient` as a namespace, this means you are using an older version. On 3 Dec, 2018 in 166e259a4d7282a47cb418608c22bfaa68730e60 the main file `TranslateClient.php` has been renamed to `GoogleTranslate.php`, and the docs/readme has been also updated to reflect these changes.

Please make sure you are using the latest version, and you will be able to use the `GoogleTranslate` class correctly.

**Comment by Stichoza** [comment]
There is a note about older docs in readme. I added it as soon as I released the new version
