### ISSUE TITLE
cURL Error 77. error setting certificate verify locations

### ISSUE THREAD

**Issue by krisnantobi** [Stichoza/google-translate-php#105]
### Error message
```
cURL error 77: error setting certificate verify locations: CAfile: C:\xampp\apache\bin\curl-ca-bundle.crt CApath: none (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```
### Error when call translate method.
```
$tr = new GoogleTranslate(); // Translates to 'en' from auto-detected language by default
$tr->setSource('en'); // Translate from English
$tr->setSource(); // Detect language automatically
$tr->setTarget('ka'); // Translate to Georgian
echo $tr->translate('Hello World!'); // error when call this method transalte()
```
### I try this but error too.
```
 echo GoogleTranslate::trans('Hello again', 'ka', 'en');exit();
```

please how to fix this?

**Comment by frzsombor** [comment]
This looks like a PHP configuration error, not related to this library.
Try search for solutions on Google.

A few links I've found:
- https://stackoverflow.com/questions/30240840/laravel-5-socialite-curl-error-77-error-setting-certificate-verify-locations
- https://stackoverflow.com/questions/24611640/curl-60-ssl-certificate-unable-to-get-local-issuer-certificate
- https://github.com/guzzle/guzzle/issues/1935#issuecomment-371756738

**Comment by Stichoza** [comment]
Thank you @frzsombor 🤘

**Comment by rizkyhaksono** [comment]
> This looks like a PHP configuration error, not related to this library. Try search for solutions on Google.
> 
> A few links I've found:
> 
> * https://stackoverflow.com/questions/30240840/laravel-5-socialite-curl-error-77-error-setting-certificate-verify-locations
> * https://stackoverflow.com/questions/24611640/curl-60-ssl-certificate-unable-to-get-local-issuer-certificate
> * [GuzzleHttp Exception cURL error 60: SSL certificate problem: unable to get local issuer certificate guzzle/guzzle#1935 (comment)](https://github.com/guzzle/guzzle/issues/1935#issuecomment-371756738)

Thanks man
