### ISSUE TITLE
Fatal error: Default value for parameters with a class type hint can only be NULL

### ISSUE THREAD

**Issue by ATMCgrafik** [Stichoza/google-translate-php#106]
hi, is there a solve it error?
" Fatal error: Default value for parameters with a class type hint can only be NULL ...GoogleTranslate.php  "

**Comment by frzsombor** [comment]
Please share your code, we can't help, if we don't see it

**Comment by ATMCgrafik** [comment]
error : " Fatal error: Default value for parameters with a class type hint can only be NULL in C:\xampp\htdocs\LISAN\google-translate-php-master\src\GoogleTranslate.php on line 109 "

my code : "

require 'src/GoogleTranslate.php';
use Stichoza\GoogleTranslate\GoogleTranslate;
$tr = new GoogleTranslate('tr'); // Translates into English
echo $tr->translate('merhaba!');

"

**Comment by frzsombor** [comment]
This project (as you can see in [composer.json](https://github.com/Stichoza/google-translate-php/blob/42326015f1e8870e92d4d6ad8a48cc22564013ea/composer.json#L14)) requires PHP ^7.1 (means v7.1 and above).
It looks like you are using an older version of PHP, which is not supported.
Please update your PHP version.

**Comment by ATMCgrafik** [comment]
OK. when upgrade to give error " Fatal error: Uncaught Error: Class 'GuzzleHttp\Client' not found in C:\xampp7.2\htdocs\google-translate-php-master\src\GoogleTranslate.php:111 Stack trace: #0 C:\xampp7.2\htdocs\google-translate-php-master\index.php(5): Stichoza\GoogleTranslate\GoogleTranslate->__construct('tr') #1 {main} thrown in C:\xampp7.2\htdocs\google-translate-php-master\src\GoogleTranslate.php on line 111 "

**Comment by programmer403** [comment]
This project requires some dependencies, you can see it in require array line in [composer.json](https://github.com/Stichoza/google-translate-php/blob/42326015f1e8870e92d4d6ad8a48cc22564013ea/composer.json#L13). As you can see, your project missing "guzzlehttp/guzzle" package, you can find it at [packagist.org](https://packagist.org/packages/guzzlehttp/guzzle) and install manualy, but i'm not recomended to do this manualy, will be better if you start using [Composer](https://getcomposer.org/)! And just run this command:
`composer require stichoza/google-translate-php` in command line interpreter, if you using windows look this guide how install composer on Windows with XAMPP:
[https://www.thecodedeveloper.com/install-composer-windows-xampp/](https://www.thecodedeveloper.com/install-composer-windows-xampp/)

**Comment by Stichoza** [comment]
Thanks @frzsombor and @programmer403 for your comments!
