### ISSUE TITLE
cURL error 7: Unsupported proxy scheme

### ISSUE THREAD

**Issue by neobie** [Stichoza/google-translate-php#116]
Uncaught ErrorException: cURL error 7: Unsupported proxy scheme for 'tcp://localhost:9124' (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /stichoza/google-translate-php/src/GoogleTranslate.php:306

**Comment by frzsombor** [comment]
Are you sure `tcp://localhost:9124` is a real proxy and is set up correctly? Because it looks like you are just using the example proxy configuration from [Guzzle's documentation](http://docs.guzzlephp.org/en/5.3/clients.html#proxy) as this host & port is exactly what they wrote in the docs.
