### ISSUE TITLE
gtranslate api limit?

### ISSUE THREAD

**Issue by gibigate** [Stichoza/google-translate-php#125]
The documentation says that there are limits and you need to register in google console. But in your documentation i cant find any words about it.

I think you should say detail about free limits in docs

**Comment by frzsombor** [comment]
The limitation is that Google watches the frequency of requests coming from a single IP address and if they suspect that the requests are automated based on their hight frequency, they will block the IP address where the requests are coming from, for a shorter or longer time which can vary from a few minutes to more than 12-24 hours. Unfortunately there is absolutely zero public information available on what are Google's rules for flagging IP addresses, what are the limits, how long they block IPs, etc as their abuse detection algorithm must be very complex and each case is different. You have to experiment with your usage and find out if you need proxies or not and if yes, how many. Also, there is always an easier, hassle-free way by paying for an API key usage at Google. Thats all we know.

**Comment by gibigate** [comment]
Does your library support google API?

**Comment by frzsombor** [comment]
This library is not using the official Google translate API. If you are planning to use that, please check the official documentation.

**Comment by gibigate** [comment]
Thank you
