### ISSUE TITLE
Suddenly getting this error on my web

### ISSUE THREAD

**Issue by ali-chaudhry** [Stichoza/google-translate-php#127]
Client error: `GET https://translate.google.com/translate_a/single?client=webapp&hl=en&dt=t&dt=bd&dt=at&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&sl=en&tl=ur&q=1+week+ago&ie=UTF-8&oe=UTF-8&multires=1&otf=0&pc=1&trs=1&ssel=0&tsel=0&kc=1&tk=740166.882744` resulted in a `429 Too Many Requests` response:

**Comment by frzsombor** [comment]
This error has already been discussed in previous issues and you can find more info about it in the [Known Limitations](https://github.com/Stichoza/google-translate-php#known-limitations) on the project's homepage.
