### ISSUE TITLE
How can I use it in Blade

### ISSUE THREAD

**Issue by reigningkingforever** [Stichoza/google-translate-php#128]
Please tell me how to use this in blade views?

**Comment by Stichoza** [comment]
This is not a Laravel package, it's framework agnostic.

But you can create your own facades or Blade directives if you want, something like `@translate()` and it could use the methods of this package.

**Comment by iamB0rgy** [comment]
So, this won't work? 

`{{ GoogleTranslate::trans('{{ $items->name }}', app()->getLocale()) }}`

**Comment by Stichoza** [comment]
@iamB0rgy You shouldn't pass parameter in blade curly braces, do this instead:

```php
{{ GoogleTranslate::trans($items->name, app()->getLocale()) }}
```

**Comment by iamB0rgy** [comment]
Thank you. It worked!
