### ISSUE TITLE
PHP Intelephense ERROR

### ISSUE THREAD

**Issue by dimaslanjaka** [Stichoza/google-translate-php#129]
please fix namespace and implements.
make error message in my vscode.
![image](https://user-images.githubusercontent.com/12471057/72491611-2bff2480-384d-11ea-8eb7-09404d1dc763.png)

**Comment by Stichoza** [comment]
You see that there is actually an interface named `TokenProviderInterface` (TokenProviderInterface.php) right next to the file you have in the screenshot (GoogleTokenGenerator.php).

It's an issue with your editor. Nothing to fix here.
