### ISSUE TITLE
Please, i have an issue here and I would like that you help me with this issue.

### ISSUE THREAD

**Issue by EduardoRoc97** [Stichoza/google-translate-php#136]
![image](https://user-images.githubusercontent.com/55397247/79906469-bbe5d900-840f-11ea-8e88-460a7301bea2.png)

**Comment by frzsombor** [comment]
Please do not open a new issue twice on a project for the exactly same issue. You will not get answers faster by this, but instead you are making the owners and contributors work harder, and getting the answer even slower. Next time please continue by posting as a comment to the original issue (in this case #135)
