### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by sgodinho2020** [Stichoza/google-translate-php#139]
hello, i am using this package and i while setting up i am getting this error.

**Comment by Stichoza** [comment]
1. Read the README file.
2. Check if there are same issues already, because there are.

**Comment by mgarcia96** [comment]
But what's the solution?

**Comment by frzsombor** [comment]
As Stichoza wrote above, please, **[read the readme](https://github.com/Stichoza/google-translate-php#known-limitations)**! 
In the known limitations there is all the information you need: what can you do, and how.

**Comment by DatTran2000** [comment]
how much text is a request, bro ?
