### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by metikulos** [Stichoza/google-translate-php#140]
Fatal error</b>:  Uncaught ErrorException: Client error: `GET https://translate.google.com/translate_a/single?client=webapp&amp;hl=en&amp;dt=t&amp;dt=bd&amp;dt=at&amp;dt=ex&amp;dt=ld&amp;dt=md&amp;dt=qca&amp;dt=rw&amp;dt=rm&amp;dt=ss&amp;sl=auto&amp;tl=en&amp;q=Login&amp;ie=UTF-8&amp;oe=UTF-8&amp;multires=1&amp;otf=0&amp;pc=1&amp;trs=1&amp;ssel=0&amp;tsel=0&amp;kc=1&amp;tk=430331.41861` resulted in a `429 Too Many Requests` response:
--
  | &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;&gt;
  | &lt;html&gt;
  | &lt;head&gt;&lt;meta http-equiv=&quot;content-type&quot; content=&quot;te (truncated...)
  | in /home/skytekgh/public_html/emigroup.skytekgh.com/vendor/stichoza/google-translate-php/src/GoogleTranslate.php:311

I get the above error when i deploy to server, runs for some time and breaks. how do i solve this

**Comment by Stichoza** [comment]
You fix it by reading readme.
