### ISSUE TITLE
When Google return wrong JSON?

### ISSUE THREAD

**Issue by WinterSilence** [Stichoza/google-translate-php#144]
Can't repeat request where need [fix JSON](https://github.com/Stichoza/google-translate-php/blob/2d048a9b64a2b7084f424e65c73d6a980705e012/src/GoogleTranslate.php#L88). Can you show example?

**Comment by frzsombor** [comment]
Please describe your problem in detail. What have you tried, what was the input and response, what was the error?
No one can help if we can not reproduce the problem.

**Comment by WinterSilence** [comment]
@frzsombor resend your developers: `?` at end of issue title calling "question" :)

**Comment by Stichoza** [comment]
@WinterSilence your issue doesn't give any details. I honestly cannot understand what you're asking or what problem are you having. Please, describe it in details and provide info that @frzsombor suggested.

**Comment by WinterSilence** [comment]
@Stichoza It's not "bug" or "future request", it's only question about current code. Google return valid json, I cant find any reason for this fix and ask you why you: add this json fix?

**Comment by frzsombor** [comment]
I can't answer the question, but at least now I guess that @WinterSilence is talking about _[this](https://github.com/Stichoza/google-translate-php/blob/2d048a9b64a2b7084f424e65c73d6a980705e012/src/GoogleTranslate.php#L317-L318)_ part of the code and would like to know why we have to do a `preg_replace` on the response body, based on `$resultRegexes` (and in which cases), as it looks like we already have a valid json at that point (also I haven't tested this statement).

**Comment by WinterSilence** [comment]
@frzsombor ups.. sorry, I thought that you action bot.

**Comment by Stichoza** [comment]
@WinterSilence lol, that's why I couldn't understand what did you mean by "resend your developers" 🤣

Yeah maybe Google now sends the valid JSON but I remember that sometimes there were invalid responses containing things like `{"words":[,,"ok","yes",,,]}` and so on.

I hadn't tested it now, but I'm afraid there might be some extra commas left in Google's responses and if we remove the regex replacement, it might cause some errors.

**Comment by Stichoza** [comment]
Leaving these regex replaces as is at least for now.
