### ISSUE TITLE
Fatal error: Uncaught ErrorException: Client error GET ..

### ISSUE THREAD

**Issue by nadia-am** [Stichoza/google-translate-php#151]
I am using google-translate.php in my code but it return errors !

the error code is:
`Fatal error: Uncaught ErrorException: Client error: `GET https://translate.google.com/translate_a/single?client=webapp&hl=en&dt=t&dt=bd&dt=at&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&sl=fa&tl=en&q=%3C%21--+wp%3Aheading+--%3E%3Ch2%3E%D9%85%D8%A7+%DA%A9%D9%87+%D9%87%D8%B3%D8%AA%DB%8C%D9%85%3C%2Fh2%3E%3C%21--+%2Fwp%3Aheading+--%3E%3C%21--+wp%3Aparagraph+--%3E%3Cp%3E%D9%86%D8%B4%D8%A7%D9%86%DB%8C+%D9%88%D8%A8%E2%80%8C%D8%B3%D8%A7%DB%8C%D8%AA+%D9%85%D8%A7%3A+http%3A%2F%2Fkhazar.mwteam.ir.%3C%2Fp%3E%3C%21--+%2Fwp%3Aparagraph+--%3E%3C%21--+wp%3Aheading+--%3E%3Ch2%3E%DA%A9%D8%AF%D8%A7%D9%85%DB%8C%DA%A9+%D8%A7%D8%B2+%D8%A7%D8%B7%D9%84%D8%A7%D8%B9%D8%A7%D8%AA+%D8%B4%D8%AE%D8%B5%DB%8C+%D8%B1%D8%A7+%D8%AC%D9%85%D8%B9+%D8%A2%D9%88%D8%B1%DB%8C+%D9%85%DB%8C%DA%A9%D9%86%DB%8C%D9%85+%D9%88+%DA%86%D8%B1%D8%A7%3C%2Fh2%3E%3C%21--+%2Fwp%3Aheading+--%3E%3C%21--+wp%3Aheading+%7B%22level%22%3A3%7D+--%3E%3Ch3%3E%D8%AF%DB%8C%D8%AF%DA%AF%D8%A7%D9%87%E2%80%8C%D9%87%D8%A7%3C%2Fh3%3E%3C%21--+%2Fwp%3Aheading+--%3E%3C%21--+wp%3Aparagraph+--%3E%3Cp%3E% in .../GoogleTranslate.php on line 312`

**Comment by karrarjasim** [comment]
I have same issue , any solution?

**Comment by nadia-am** [comment]
@karrarjasim my problem was because of sanction, the server was from iran, i change it and it solved.

**Comment by frzsombor** [comment]
@nadia-am: The problem was not that your server was from Iran, but most likely the IP got banned because of too many requests, just like @karrarjasim had in #152 - therefore the answer is also the same for this issue.
