### ISSUE TITLE
Uncaught ErrorException: Client error

### ISSUE THREAD

**Issue by karrarjasim** [Stichoza/google-translate-php#152]
## I'm getting this error when I try to translate text 

`Uncaught ErrorException: Client error: `GET https://translate.google.com/translate_a/single?client=webapp&hl=en&dt=t&dt=bd&dt=at&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&sl=auto&tl=ka&q=Hello&ie=UTF-8&oe=UTF-8&multires=1&otf=0&pc=1&trs=1&ssel=0&tsel=0&kc=1&tk=655597.799635` resulted in a `429 Too Many Requests` response: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"> <html> <head><meta http-equiv="content-type" content="te (truncated...) in /home/u674981524/domains/mydomain/vendor/stichoza/google-translate-php/src/GoogleTranslate.php:311 Stack trace: #0 /home/u674981524/domains/mydomain/vendor/stichoza/google-translate-php/src/GoogleTranslate.php(228): Stichoza\GoogleTranslate\GoogleTranslate->getResponse('Hello') #1 /home/u674981524/domains/mydomain/tra.php(8): Stichoza\GoogleTranslate\GoogleTranslate->tran in /home/u674981524/domains/mydomain/vendor/stichoza/google-translate-php/src/GoogleTranslate.php on line 311`

**It was work before 2 days !
any suggestions**

**Comment by frzsombor** [comment]
As you can see, your error message clearly says that it is resulted in a `429 Too Many Requests` error, which has been already discussed in [so many issues](https://github.com/Stichoza/google-translate-php/issues?q=Too+Many+Requests) and has a dedicated paragraph [in the README.md](https://github.com/Stichoza/google-translate-php#known-limitations).
