### ISSUE TITLE
take voice word?

### ISSUE THREAD

**Issue by netwons** [Stichoza/google-translate-php#153]
im want take voice word?

**Comment by Stichoza** [comment]
Can you explain your problem?

**Comment by netwons** [comment]
I want the pronunciation&(voice) of the word

**Comment by Beilaitei** [comment]
I wanna add the new language to google translate. Show me the way.

**Comment by Stichoza** [comment]
@netwons Currently it's not possible to get an audio of pronunciation, but you can use `getRespone()` method to dig into more data. You can find things like spelling and other useful data. Audio file is a separate HTTP request on Google Translate. Hopefully I'll implement it someday.

@Beilaitei This package only supports languages which are available on Google Translate. You can't add a new language.
