### ISSUE TITLE
PHP 8 Support ?

### ISSUE THREAD

**Issue by foremtehan** [Stichoza/google-translate-php#154]
Hello folks Are there any plans to support PHP 8?

**Comment by Stichoza** [comment]
I haven't tested it on PHP 8 yet but I'm sure it will work just fine. I'll test it and add php 8.0.x support in composer.json

**Comment by dream811** [comment]
After test this in laravel 8, I met this error. 
ErrorException
Client error: `GET https://translate.google.com/translate_a/single?client=webapp&hl=en&dt=t&dt=bd&dt=at&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&sl=en&tl=kr&q=Hello+again&ie=UTF-8&oe=UTF-8&multires=1&otf=0&pc=1&trs=1&ssel=0&tsel=0&kc=1&tk=589066.970356` resulted in a `400 Bad Request` response: <html lang=en><meta charset=utf-8><meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width"><ti (truncated...)
http://127.0.0.1:8000/scratchSellPrepareCheck
![Uploading image.png…]()

**Comment by dream811** [comment]
After test this in laravel 8, I met this error. 
ErrorException
Client error: `GET https://translate.google.com/translate_a/single?client=webapp&hl=en&dt=t&dt=bd&dt=at&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&sl=en&tl=kr&q=Hello+again&ie=UTF-8&oe=UTF-8&multires=1&otf=0&pc=1&trs=1&ssel=0&tsel=0&kc=1&tk=589066.970356` resulted in a `400 Bad Request` response: <html lang=en><meta charset=utf-8><meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width"><ti (truncated...)
http://127.0.0.1:8000/scratchSellPrepareCheck
![image](https://user-images.githubusercontent.com/45660446/103148176-06d2a000-4798-11eb-94c9-21e88ee0dfdd.png)

**Comment by Stichoza** [comment]
Supported as of https://github.com/Stichoza/google-translate-php/releases/tag/v4.1.2
