### ISSUE TITLE
连续求情几口

### ISSUE THREAD

**Issue by jiatengfei** [Stichoza/google-translate-php#155]
![image](https://user-images.githubusercontent.com/23369658/101760141-73ea0280-3b15-11eb-9b54-21afb98413ca.png)

**Comment by Stichoza** [comment]
Guess I'll have to use this package to translate the title of this issue 🤷🏼‍♂️

**Comment by jiatengfei** [comment]
> 猜猜我将不得不使用该程序包来翻译本期杂志的标题🤷🏼‍♂️
我的意思是  目前在使用这个包做翻译  但是总是报这个错误 导致程序一直中断，该进程直接终止退出了， 该错误会是什么原因造成的呢？
