### ISSUE TITLE
Randomly 403 Forbidden

### ISSUE THREAD

**Issue by nicolasdevai13** [Stichoza/google-translate-php#156]
Hello,

I have a randomly 403, I already try this fix https://github.com/Stichoza/google-translate-php/issues/119#issuecomment-558078133

But this error is random, for example I am on the foreach loop and I have this error on https://translate.google.com/translate_a/single?client=webapp&hl=en&dt=t&dt=bd&dt=at&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&sl=en&tl=fr&q=Internet+Information+Services+%28IIS%29+is+a+web+server+created+by+Microsoft+for+use+with+Microsoft+Windows.+Please+mention+which+version+of+IIS+you%26%2339%3Bre+running+either+in+your+question+or+by+adding+a+version+specific+tag.&ie=UTF-8&oe=UTF-8&multires=1&otf=0&pc=1&trs=1&ssel=0&tsel=0&kc=1&tk=937267.556621 request.

If I took the same "sting" and translate it out of the foreach all is ok.

Can you help me please ?

Thanks

**Comment by Stichoza** [comment]
That error is random, there is a chance that it's related to Error 429 ([rate limiting](https://github.com/Stichoza/google-translate-php#known-limitations)), i.e. you're sending requests too quickly (that foreach loop). Try translating other set of simple strings (no special characters, no html) in a same loop and see if you get the same error.

**Comment by nicolasdevai13** [comment]
Thanks for your reply,

I will try this but I also had a Error 429 for to many request independant of the Error 403.

**Comment by wifirevaithi** [comment]
Facing the same Problem

**Comment by Stichoza** [comment]
This is described in [known-limitations](https://github.com/Stichoza/google-translate-php#known-limitations) section and happens for unknown reasons. Same happens on Google Translate we app, not related to this package.

As of v5.1.0 this error is contained in `TranslationRequestException`
