### ISSUE TITLE
Http Code 404

### ISSUE THREAD

**Issue by twitf** [Stichoza/google-translate-php#158]
# request
`http://translate.google.cn/translate_a/single?client=webapp&hl=en&dt=t&dt=bd&dt=at&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&sl=en&tl=zh&q=Product+Identifier+already+in+use+in+combination+with+%22Condici%C3%B3n+del+Producto%22.+&ie=UTF-8&oe=UTF-8&multires=1&otf=0&pc=1&trs=1&ssel=0&tsel=0&kc=1&tk=436602.39428`

# response
> Http Code 404

## Response Body ↓↓↓
```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>NoSuchKey</Code>
    <Message>The specified key does not exist.</Message>
    <RequestId>5FF802F564BB2931320E32A1</RequestId>
    <HostId>i-bosity-com.oss-cn-hongkong.aliyuncs.com</HostId>
    <Key>sorry/index</Key>
</Error>
```
But when I directly get the request through the browser, it is normal. Has Google detected that I have not purchased their service?

**Comment by Stichoza** [comment]
Are you sure there is no other issues? Like network bans/limitations? It doesn't look like an error from Google, the domain aliyuncs.com belongs to Alibaba. Looks like you're accessing from China and Google blocked there. That's my guess, please provide more details if possible

**Comment by twitf** [comment]
I visited it again today. Maybe it has something to do with the network. "FHQ."
