### ISSUE TITLE
Accuracy Of Google Translate

### ISSUE THREAD

**Issue by Blair2004** [Stichoza/google-translate-php#164]
Hi, 
Thank you for your package, i've successfully launched a multilingual website. However, i have a concern. 
In fact, i noticed there is a major difference between the Google Translate as used on the package and the Google Translate (the website). I tried to translate same sentences on both, but it looks like both translate differently. Does the package uses an old version of Google Translate?

**Comment by Stichoza** [comment]
The same issue was opened several minutes ago. I'll close this one as duplicate
