### ISSUE TITLE
Wich proxy do you recommend?

### ISSUE THREAD

**Issue by arcanaer** [Stichoza/google-translate-php#169]
Hello, i wanted to know what proxy do you recommend to use with this repo, i thinking to do a lot of requests, so i need that google doesn't ban my server ip. I need to do around of 200 000 request daily, so i couldn't pay the official api.

**Comment by Stichoza** [comment]
I haven't used any third-party services. I only used one server that I setup using [Squid](http://www.squid-cache.org). You can do a quick research, there are many articles recommending several proxy services.
