### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by cankilinc** [Stichoza/google-translate-php#174]
I started getting this error today. It was working good before ( yesterday ).

Fatal error: Uncaught ErrorException: Client error: `GET https://translate.google.com/translate_a/t?client=t&hl=en&dt=t&sl=auto&tl=tr&q=Long-term+investors+are+keeping+their+hands+strong+during+the+recent+decline+in+Bitcoin+price&ie=UTF-8&oe=UTF-8&multires=1&otf=0&pc=1&trs=1&ssel=0&tsel=0&kc=1&tk=154985.290327` resulted in a `404 Not Found`

**Comment by NoZTurn** [comment]
I also face the same problem, try change https://translate.google.com/translate_a/t? ..... to https://translate.google.com/translate_a/single? ....

**Comment by NoZTurn** [comment]
I also face the same problem, try change https://translate.google.com/translate_a/t? ..... to https://translate.google.com/translate_a/single? ....
