### ISSUE TITLE
How can I translate full page in Multiple Languages ?

### ISSUE THREAD

**Issue by dev6trivediinfotech** [Stichoza/google-translate-php#175]
How can I translate full page in Multiple Languages?
I want to translate full page using this package in laravel. Is your package provide such type of functionality ? If not, can you please suggest another Free package or API for this type of functionality ?  

Thank You :)

**Comment by Stichoza** [comment]
Translating full page means you need to translate whole HTML, which is not supported (you can still try, but most probably the HTML will be broken). Even the official package does not support this as far as I know.

What Google does when you translate a page on the translate.google.com is that it parses the HTML in the browser and sends multiple requests with text contents of specific elements. Example in the screenshot:

![image](https://user-images.githubusercontent.com/1139050/145118842-6a185f16-6f55-44cd-b952-b16c49f16a78.png)
