### ISSUE TITLE
Not an issue, but what if I want to use my Google Cloud API Key to your Package. It is just because your package functions are so easy to use. Maybe I can use it with my API keys for Professional purpose

### ISSUE THREAD

**Issue by drogon-codes** [Stichoza/google-translate-php#177]

**Comment by Stichoza** [comment]
I think Google's official package is not that different when compared to this package. I don't think that it would be a good idea to include official library into this package for multiple reasons but mainly because of maintenance of the repo.

Thanks for your suggestion though.
