### ISSUE TITLE
CAPTCHA

### ISSUE THREAD

**Issue by michzio** [Stichoza/google-translate-php#18]
I think there is captcha problem when making frequent calls from given ip address

**Comment by Stichoza** [comment]
Can you provide any example? screenshots, error messages, anything

**Comment by michzio** [comment]
![screen shot 2015-04-08 at 23 57 10](https://cloud.githubusercontent.com/assets/10163187/7056318/17caf82e-de4b-11e4-97d8-3d6256dbd641.png)

**Comment by Stichoza** [comment]
Yeah, Google Translate is a paid API. So Google will eventually block your IP or ask to solve Captcha to proceed with frequent requests. Try to change this package and pull in [fzaninotto/faker](https://github.com/fzaninotto/Faker) to send requests with random User Agent headers. I'm pretty sure Google will still require captcha.

This is not a production ready package, it's just a workaround. See [readme#disclaimer](https://github.com/Stichoza/google-translate-php#disclaimer).

**Comment by Stichoza** [comment]
I guess this issue can be closed. I'll link this in readme.

**Comment by divinity76** [comment]
do we at least throw some kind of \RuntimeException when this happens?

**Comment by alisher717** [comment]
gives such an error? [https://skr.sh/sCADJpLwFwq?a](url)

**Comment by alisher717** [comment]
How to solve this problem. works then, does not work, after a while works again
