### ISSUE TITLE
setUrl is not work for me 

### ISSUE THREAD

**Issue by qingjiuzhubei** [Stichoza/google-translate-php#182]
I am a user in mainland China. I tried to update the default translation address to https://translate.google.cn/, but setUrl didn't work. Is it redirected to google.com by default? Need to add request headers when I request?

![image](https://user-images.githubusercontent.com/19279780/163307523-dd4d5c36-e2a8-4a63-af50-45164d857ee9.png)

![image](https://user-images.githubusercontent.com/19279780/163307496-daed2bc9-823f-45d7-844c-73fa4582a391.png)

**Comment by fengyun21** [comment]
遇到同样的问题，楼主解决了嘛？
