### ISSUE TITLE
setUrl() It is not available in mainland China

### ISSUE THREAD

**Issue by pctcocom** [Stichoza/google-translate-php#184]
$tr->setUrl('http://translate.google.cn/translate_a/single'); 

When you visit http://translate.google.cn/translate_a/single http://translate.google.cn/translate_a/single to jump back to http://translate.goo gle.com/translate_a/single or display 400 is not accessible

I'm in mainland China right now

"version": "v4.1.6"

**Comment by Stichoza** [comment]
I added a test that proves that URL change is possible. If there is a redirect to ".com" domain that means it's done by Google for some reason. Same applies to #182 and #183
