### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by nielsb02** [Stichoza/google-translate-php#186]
Hi, the translator works really good, thanks!

But there is one problem when I do a lot of (mostly small text) translations, the token generator uses a lot of memory. Because of the PHP::mb_convert_encoding function. 

Here is an example, I did about 500 translations which used a total of 64MB. 

Version: v4.1.6

![afbeelding](https://user-images.githubusercontent.com/72166173/194709386-4d6fd6b8-fad4-4e6a-9af5-1f2257f33c0d.png)

**Comment by nielsb02** [comment]
I saw this pull request: https://github.com/Stichoza/google-translate-php/pull/145 and tried it out myself, works like a charm! Thanks WinterSilence.

**Comment by Stichoza** [comment]
Hello! Can you provide the full example of code?

**Comment by Stichoza** [comment]
#145 is merged

**Comment by nielsb02** [comment]
Hi, didn't see your response but I simply used the token generator file of this pull request as a custom token generator. Thank you for merging tho!
