### ISSUE TITLE
Country an cities sometimes are not translated

### ISSUE THREAD

**Issue by Mattia-Marchiorato** [Stichoza/google-translate-php#188]
Hello @Stichoza , first of all thanks for your package ;)
We faced an issued with countries translations, if you try to translate from it_IT to en_EN some countries or cities is not working:

You can try with:
- Italia
- Roma 

But if you try to tranlate more than one words like:
- Che bella italia

is woking correctly.

Thanks

MM

**Comment by Stichoza** [comment]
Which version are you using? Can you also provide exact sentence in which cities are not translated? I tried several variants and each time Roma was translated to Rome.

**Comment by Mattia-Marchiorato** [comment]
Hello @Stichoza , is the 4.1.6
You can try with "Roma" or "Francia", just the single word from IT to EN.

Thanks

MM

**Comment by Stichoza** [comment]
Both words are translated correctly.

Try newer version of this package or check [translation quality](https://github.com/Stichoza/google-translate-php#translation-client-quality) part in readme.


<img width="400" alt="image" src="https://user-images.githubusercontent.com/1139050/212774818-97a7ece6-a8d9-4c8e-9412-93095b70f0c7.png">

**Comment by Mattia-Marchiorato** [comment]
@Stichoza ,

ok we updated to 4.1.7 and seems better.

Thank you!
