### ISSUE TITLE
UTF8 Issues

### ISSUE THREAD

**Issue by SBerda** [Stichoza/google-translate-php#19]
Hello,
You guys did a really great job but I have some issues when I translate english to french for exemple:
Chief Executives => directeurs GÃ©nÃ©raux.
Do you have any idea why?
Thank you
Best regards
SBerda

**Comment by Stichoza** [comment]
That problem is not caused by this package. It works fine with encodings.

Change your browsers default encoding or set it explicitly [from html](http://stackoverflow.com/questions/14669352/is-the-charset-meta-tag-required-with-html5).
