### ISSUE TITLE
How do I swap to using my own paid api key?

### ISSUE THREAD

**Issue by xitude** [Stichoza/google-translate-php#191]
Hello! I am facing limitation throttling problems and I am interested in upgrading to a paid version. However, I am unable to locate the documentation on how to begin using my key. Can you assist me?

**Comment by Stichoza** [comment]
This package does not support translations with API key. In this case, you should use the official [google/cloud-translate](https://cloud.google.com/translate/docs/reference/libraries/v2/php) package instead.
