### ISSUE TITLE
Loading Problem.

### ISSUE THREAD

**Issue by AamirAnwar3311** [Stichoza/google-translate-php#192]
Hi, I am using this package. But it is taking a very long time. I have an API key that is paid. If I have to put that, then please let me know. It takes around 50-70 seconds.

**Comment by joe820912boy** [comment]
I think this package didn't need any api key when you use it,

it translate like you send the request when you use the google translate,

doesn't cost you so much time where you said about 50~70 seconds.

**Comment by Stichoza** [comment]
If you have a paid API key you should use the official package by Google instead. This one is free package without keys
