### ISSUE TITLE
Can you give me a list of free Proxies that I can use so that translation is not blocked in the future?

### ISSUE THREAD

**Issue by richardsonoge** [Stichoza/google-translate-php#194]
Hello
The proxy I showed you last time didn't work. Can you give me a list of proxies I can use for free please? I would like you to give me at least one example of integration as well.

```
<?php
require_once 'vendor/autoload.php'; // Include Composer's autoloader
use Stichoza\GoogleTranslate\GoogleTranslate;

// $tr = new GoogleTranslate('fr');
$tr = new GoogleTranslate('fr');
// Set proxy to tcp://localhost:8090
$tr->setOptions([
    'proxy' => 'socks5://localhost:1080'
]);

$text = $tr->translate('Hello World!');
echo $text; // Output: en
```

My question refers to **[this question.](https://github.com/Stichoza/google-translate-php/issues/193)**

**Comment by Stichoza** [comment]
Sorry, I cannot provide list of proxy servers.
