### ISSUE TITLE
Ignore escaped keys on translations

### ISSUE THREAD

**Issue by kylemilloy** [Stichoza/google-translate-php#198]
# Problem

Right now when sending keys to be translated we include serialization keys like:

```php
__('Hello :name', ['name' => $user->name])
```

And when we send this to get translated we get:

```js
// en.json
"Hello :name": "Hello :name"
// fr.json
"Hello :name": "Hello :nom"
```

# Solution

Provide a way to ignore serialization keys or modify the match rules for identifying these.

**Comment by Stichoza** [comment]
It's a known issue, similar to #167. Unfortunately Google doesn't understand such tags and it translates everything.

**Comment by kylemilloy** [comment]
Sure. But surely there's a change we can make here that what gets sent to Google doesn't have to be translated. I was thinking of a solution where we use preg_replace to match keys, for example the string `Hello :name` and have that transform into `Hello $0` which gets sent to Google. On the return trip, we replace the key back so that we get `Bonjour $0` and then just swap back in our value here with `Bonjour :name`

If you reopen this, I can try to make the appropriate changes and submit a PR.

**Comment by Stichoza** [comment]
That is actually a great idea! Laravel and most of PHP frameworks use `:variable` syntax so it will cover most of use cases.

**Comment by kylemilloy** [comment]
Okay. I'll focus on using colons as the default delimiter but maybe give the option to provide your own pattern or resolver method.
