### ISSUE TITLE
Error: Class "Stichoza\GoogleTranslate\GoogleTranslate" not found in file

### ISSUE THREAD

**Issue by ShazinAhmed97** [Stichoza/google-translate-php#200]
when it runs on the local server there is no issue at all its working perfect .. but when i test it on liver server this error shows i tried many changes but no use 

`use Stichoza\GoogleTranslate\GoogleTranslate;`

`private function translateProducts($products, $targetLanguage)
    {
        $translator = new GoogleTranslate();`

        // Set the target language
        $translator->setTarget($targetLanguage);

        if (is_array($products))
        {
            $translatedProducts = [];
            foreach ($products as $product) {
                $translatedProducts[] = $translator->translate($product);
            }
        }
        else
        {
            $translatedProducts = $translator->translate($products);
        }

        //print_r($translatedProducts); die();
        return $translatedProducts;
    }`
this is my function

**Comment by ShazinAhmed97** [comment]
yes i have 
``"autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/",
            "Stichoza\\GoogleTranslate\\" : "vendor/stichoza/google-translate/src)"
        }
    },``

**Comment by Stichoza** [comment]
I cannot reproduce this bug, can you list steps for it?

**Comment by ShazinAhmed97** [comment]
is there any restrictions for live server ?

**Comment by Stichoza** [comment]
There are no restrictions. Make sure you're deployment is correct

**Comment by miztizm** [comment]
I encountered the same error after installation, but after a few minutes, it worked fine (I believe it's a vscode issue).
