### ISSUE TITLE
Bug report: preserveParameters gives unexpected results when translating to French

### ISSUE THREAD

**Issue by charescape** [Stichoza/google-translate-php#201]
### What steps will reproduce the problem?

```php
$google = new GoogleTranslate();

$google->setSource('en');
$google->setTarget('fr');

echo $google->preserveParameters('#\{([^}]+)}#')->translate('What is {real_q_encoded}?');
```

### What is the expected result?
`Qu'est-ce que {real_q_encoded} ?`

### What do you get instead?
`Qu'est-ce que {0} $ ?`

**Comment by kylemilloy** [comment]
I just ran into this myself...I was the one that introduced the change...If we change the encoding to #{0} it _should_ do it...seems localized to only some situations when doing french. I'll make a PR.
