### ISSUE TITLE
How can I translate my page web HTML into your library?

### ISSUE THREAD

**Issue by richardsonoge** [Stichoza/google-translate-php#206]
Hi there!

I have my page web HTML [https://filesamples.com/samples/code/html/sample1.html](https://filesamples.com/samples/code/html/sample1.html) and would like to use your library to translate it. How can I do it? If you don't have it... Can you please add it for me?

**Comment by Stichoza** [comment]
Hi! Check the pinned issue on the repo

duplicate of #23

**Comment by richardsonoge** [comment]
I've checked it and I still can't translate it correctly without losing the meaning of the HTML file. What should I do?
