### ISSUE TITLE
bump ver

### ISSUE THREAD

**Issue by kylemilloy** [Stichoza/google-translate-php#210]
Can we get a bump ver for the fixes for string translations from like #202 and #208

Packagist is still pointing at 5.1.3 and I'd like to lock to a ver instead of a dev release.

# 🙏 🙏 🙏 🙏

**Comment by Stichoza** [comment]
Pushed v5.1.4 🙌🏼  Thanks for reminding!

**Comment by kylemilloy** [comment]
That was speedy! Thank you!
