### ISSUE TITLE
Transliteration with preserve parameters

### ISSUE THREAD

**Issue by Shun-Ibiki** [Stichoza/google-translate-php#212]
Could the `preserve Parameters()` be used to get transliteration of the text?

**Comment by Stichoza** [comment]
I didn't understand what you mean. Can you explain?

**Comment by Shun-Ibiki** [comment]
Currently I using `$responseArray = $tr->getResponse('こんにちは')` to get romaji/tranliteration of Japanese text. Bur when dealing with html tag, the transliteration of the tag will be messed up. So can I use `preserveParameters()` to do this job cleanly?

**Comment by Stichoza** [comment]
No it only works with parameters for injecting strings. Params like `:this` or `{{this}}` or any regex that doesn't get messed up by Google Translate. HTML tags are not supported. There is a pinned issue (#23) about that topic
