### ISSUE TITLE
Translating with HTML

### ISSUE THREAD

**Issue by stewardjornsen** [Stichoza/google-translate-php#23]
Thanks for the translator script. I think the issue is more with Google than with your script. if html is translated, </li> ends up as </  li> which isn't right. So one can't translate an article that has paragraphs and html elements without it breaking. So my question is more of a tip:

Can I possibly translate html without damaging the html codes? If yes, how? Any suggestion is appreciated.

**Comment by Stichoza** [comment]
Yes, this is [a problem with Google Translate](https://translate.google.com/#auto/de/%3Cul%3E%0A%20%20%20%3Cli%3Eone%3C%2Fli%3E%0A%20%20%20%3Cli%3Etwo%3C%2Fli%3E%0A%3C%2Ful%3E) itself.

I guess you can write a regex (or just `str_replace`) to replace `< /` with `</` (without space). But anyways, do not depend on "hacks" like that.

**Comment by Stichoza** [comment]
You should do it with regex as the space is after `/`.

**Comment by stewardjornsen** [comment]
Any examples? It really misses up everything...

On Thu, May 14, 2015 at 8:03 PM, Levan Velijanashvili <
notifications@github.com> wrote:

> You should do it with regex as the space is after /.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Stichoza/google-translate-php/issues/23#issuecomment-102139163>
> .
>



-- 
*Steward Godwin Jornsen*
+234.803.9468.290
StewardXpress Nigeria Limited
www.stewardxpress.com


In His Name Bible Church
www.inhisnamebiblechurch.com <http://www.ihnbc.com>

*This mail should only be used for the purpose of which it was sent and by
the receiver of this mail only. We guarantee that this mail is sent free of
all viruses or spyware. You are advised to scan attachments before opening.
StewardXpress/In His Name Bible Church is not responsible for how you used
the provided data.*

**Comment by Stichoza** [comment]
```php
$result = $t->translate('html string here');
$result_with_correct_html = preg_replace('/\/\s/', '/', $result);
```

That's it.

**Comment by stewardjornsen** [comment]
Thank you very much. I shall give that a try. If that works great, you
could as well extend the class to have that html return object. That could
be cool, don't you think?

Thanks again.

On Wed, May 20, 2015 at 11:00 AM, Levan Velijanashvili <
notifications@github.com> wrote:

> $result = $t->translate('html string here');$result_with_correct_html = preg_replace('/\/\s/', '/', $result);
>
> That's it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Stichoza/google-translate-php/issues/23#issuecomment-103831917>
> .
>



-- 
*Steward Godwin Jornsen*
+234.803.9468.290
StewardXpress Nigeria Limited
www.stewardxpress.com


In His Name Bible Church
www.inhisnamebiblechurch.com <http://www.ihnbc.com>

*This mail should only be used for the purpose of which it was sent and by
the receiver of this mail only. We guarantee that this mail is sent free of
all viruses or spyware. You are advised to scan attachments before opening.
StewardXpress/In His Name Bible Church is not responsible for how you used
the provided data.*

**Comment by Stichoza** [comment]
I really appreciate your idea, but I don't think so. This package has a very simple API - just three methods and that's it. This is not intended to translate HTML strings. If so, then why not add JSON or XML support? It will lead to very impure code. Bringing back HTML tags is one simple regex (noted above). It's not worth adding extra functionality for that. Plus, I'm not sure this regex will fix all problems with translated HTML.

P.S I won't close this issue for now. Let it be open for further public discussions.

**Comment by Stichoza** [comment]
The official paid API has [`format` attribute](https://cloud.google.com/translate/v2/using_rest#query-params) where you can set that translated text is HTML.

So if we could find any way* to make it work with HTML strings without damaging tags and avoiding usage of extra "hacky" regexes, it would be really cool.

_* - Maybe it can be achieved using some [attribute in URL string](https://github.com/Stichoza/google-translate-php/blob/b11ae50499b9818be17a404d87be5ee7d8cdceea/src/Stichoza/GoogleTranslate/TranslateClient.php#L55-L68)._

**Comment by stewardjornsen** [comment]
Thanks,
No point anyway. Google sometimes translates the names of classes and Tag
ID which does seriously scramble website functionality.

Steward

On Thu, May 21, 2015 at 1:01 AM, Levan Velijanashvili <
notifications@github.com> wrote:

> The official paid API has format attribute
> <https://cloud.google.com/translate/v2/using_rest#query-params> where you
> can set that translated text is HTML.
>
> So if we could find any way* to make it work with HTML strings without
> damaging tags and avoiding usage of extra "hacky" regexes, it would be
> really cool.
>
> ** - Maybe it can be achieved using some attribute in URL string
> <https://github.com/Stichoza/google-translate-php/blob/b11ae50499b9818be17a404d87be5ee7d8cdceea/src/Stichoza/GoogleTranslate/TranslateClient.php#L55-L68>.*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Stichoza/google-translate-php/issues/23#issuecomment-104075424>
> .
>



-- 
*Steward Godwin Jornsen*
+234.803.9468.290
StewardXpress Nigeria Limited
www.stewardxpress.com


In His Name Bible Church
www.inhisnamebiblechurch.com <http://www.ihnbc.com>

*This mail should only be used for the purpose of which it was sent and by
the receiver of this mail only. We guarantee that this mail is sent free of
all viruses or spyware. You are advised to scan attachments before opening.
StewardXpress/In His Name Bible Church is not responsible for how you used
the provided data.*

**Comment by Stichoza** [comment]
That's exactly what I mean "without damaging tags". Yea, I think there's no way to translate HTML using [this](https://github.com/Stichoza/google-translate-php/blob/b27e49a6af41dfef709521785e06c39367152f2b/src/Stichoza/GoogleTranslate/TranslateClient.php#L49) service url.

**Comment by dimaslanjaka** [comment]
Can you make autoload versions ?. There i using hosting. Not supported for installing new php library

**Comment by vielhuber** [comment]
The official API has way better support for html tags. When reverse engineering the current inline translation of Google Chrome, these results are also very good (and with correct html tags).

I've extracted the following parameters, Google Chrome currently uses:

![image](https://user-images.githubusercontent.com/3183737/76812762-3bbbca80-67f6-11ea-986b-bd047816db86.png)

Can anybody check if some parameters are missing in this library?

**Comment by thanhansoft** [comment]
Please help me regex replace: class = "row" => class="row"

**Comment by RokonuzzamanJhinuk** [comment]
bro  you can  use this  to translate  your html  database data to any language using this package.
just use like this----  First decode the html code.. then use inside this package translate function.

<p class="mb-lg-5 mb-3">
           {!!  \Stichoza\GoogleTranslate\TranslateClient::translate( Session::get('s_lang'), Session::get('t_lang'), html_entity_decode(str_limit($n->body,500) ) ) !!}
 </p>

**Comment by milahu** [comment]
> The official paid API has [`format` attribute](https://cloud.google.com/translate/v2/using_rest#query-params) where you can set that translated text is HTML.

the paid API also allows `<div class="notranslate">...</div>` to disable translation for specific terms

> So if we could find any way* to make it work with HTML strings without damaging tags and avoiding usage of extra "hacky" regexes, it would be really cool.
> 
> _* - Maybe it can be achieved using some [attribute in URL string](https://github.com/Stichoza/google-translate-php/blob/b11ae50499b9818be17a404d87be5ee7d8cdceea/src/Stichoza/GoogleTranslate/TranslateClient.php#L55-L68). The actual [translate.google.com](http://translate.google.com) doesn't have option to set type to HTML, so I'm not sure we can find an easy solution for this_

yes, it was not easy ^^ but i got it working in my [translate.js](https://github.com/milahu/alchi/blob/master/src/alchi-book/scripts/translate.js) script
also see my post in [Prohibit the translation of pieces of text in Google Translate](https://webapps.stackexchange.com/a/154694/273346)
