### ISSUE TITLE
guzzle dependency

### ISSUE THREAD

**Issue by natostanco** [Stichoza/google-translate-php#25]
Does it have a problem with guzzle 6?

apparently it does?

    Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Passing in the "body" request option as an array to send a POST request has been deprecated. Please use the "form_params" request option to send a application/x-www-form-urlencoded request, or a the "multipart" request option to send a multipart/form-data request.'

**Comment by Stichoza** [comment]
Yes, I should update dependency from `~5.0` to `~6.0`. Can you provide a pull request to update this package from 5 to 6?

**Comment by Stichoza** [comment]
fixed in #27
