### ISSUE TITLE
Its not working for me  :(

### ISSUE THREAD

**Issue by A4mahi** [Stichoza/google-translate-php#28]
I am working with the version 2.0.3 and following is my code its showing blank page

<?php
include ("GoogleTranslate.php");//in same dir
use Stichoza\Google\GoogleTranslate;//namespace in class
$tr = new GoogleTranslate("en", "ka");
echo $tr->translate("Hello World!");
?>

**Comment by A4mahi** [comment]
![image](https://cloud.githubusercontent.com/assets/11684518/9021096/7649d6ba-384e-11e5-8b2b-48c1b09fe1d1.png)
my code 


![image](https://cloud.githubusercontent.com/assets/11684518/9021099/8ca20e5a-384e-11e5-8bbe-3d0694ae2fbd.png)

my output

**Comment by Stichoza** [comment]
It's strange that you are including GoogleTranslate.php file. Have you installed all dependencies properly using Composer?

**Comment by A4mahi** [comment]
Thanks for the response now i am using latest version and its working fine

Thakns

Anil Baweja
Web Developer
