### ISSUE TITLE
Php 5.4 Version Not Working

### ISSUE THREAD

**Issue by patelsagar** [Stichoza/google-translate-php#38]
Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) 
google-translate/src/Stichoza/GoogleTranslate/TranslateClient.php on line 92
PHP Version 5.4.45 Not Working And PHP Version 5.4

**Comment by Stichoza** [comment]
Yes.

 - Required PHP version for this package is 5.5.0 as you can see in [composer.json](https://github.com/Stichoza/google-translate-php/blob/master/composer.json#L14)
 - Also, Guzzle HTTP (dependency of this package) [requires PHP 5.5](http://guzzle.readthedocs.org/en/latest/overview.html#requirements) also.
 - We [don't even test](https://github.com/Stichoza/google-translate-php/blob/master/.travis.yml) 5.4 version.
 - And after all, PHP 5.4 is [not a supported version](php versions in use) anymore.

**Comment by patelsagar** [comment]
But i am using php 5.4
php 5.4 Use the google-translate-php library

**Comment by Stichoza** [comment]
Sorry, not sorry. PHP 5.4 is not supported.

**Comment by patelsagar** [comment]
thank you @Stichoza
