### ISSUE TITLE
Fatal error: Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings.

### ISSUE THREAD

**Issue by kmaxat** [Stichoza/google-translate-php#46]
Fatal error: Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.' in /Users/kmaxat/PhpstormProjects/untitled1/vendor/stichoza/google-translate-php/src/Stichoza/GoogleTranslate/Tokens/GoogleTokenGenerator.php:79

**Comment by kmaxat** [comment]
php - v 
PHP 5.6.16 (cli) (built: Nov 27 2015 10:28:22)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

**Comment by Stichoza** [comment]
It's about your configuration. Not related to this package.
