### ISSUE TITLE
[3.2] ErrorException in TranslateClient.php line 298

### ISSUE THREAD

**Issue by stevebauman** [Stichoza/google-translate-php#54]
An exception is thrown when trying to generate a translation from a string or array.

On line 298 of the translate client, it seems to loop over a non-existent array:

```php
foreach ($responseArrayForLanguages as $itemArray) {
    // $itemArray is actually a string.
    foreach ($itemArray as $item) {
        if (is_string($item)) {
            $detectedLanguages[] = $item;
        }
    }
}
```

**Comment by Stichoza** [comment]
Are you using the latest version of this package?

**Comment by stevebauman** [comment]
*facepalm*, no I'm not, checked the source against my local copy. Apologies!
