### ISSUE TITLE
Multi sentence translation doesn't seem to work

### ISSUE THREAD

**Issue by tomvo** [Stichoza/google-translate-php#72]
```
$tr = new TranslateClient; //($fromLanguage, $toLanguage);
$tr->setSource('de');
$tr->setTarget('en');
var_dump($tr->translate(['fahrrad', 'schule', 'baum']));
```

returns a one element array with just the letter `f`:

```
array (size=1)
  0 => string 'f' (length=1)
```

Any clue on why this can be happening?

**Comment by Stichoza** [comment]
Yes, the array translation is broken and that's why the CI build badge is red :(

**Comment by armantsh** [comment]
The solution I have found for this, that is more or less accurate, is to implode texts with " \r\n ", and then call the translate on this string. After you can use explode(PHP_EOL, $results); to get translations. There is also some limitation for string length, that is why I am sending text which length is no more then 2000. So in case you have 8000 characters, you should call translate function 4 or 5 times. This is not very accurate, but it is something at least.

**Comment by tomvo** [comment]
@Stichoza yeah i've seen that the issue is with the array nesting level. But the solution seems too simple just to change the nesting level, right?

But there are two issues here, when I check the result of the `getResponse()` method on a multi-sentence translation it only returns one translation: 

`[[["Katze","cat",,,2]],,"en"]`

I'm not sure how it has worked in the past but when I look at the request I see that the individual sentences are passed in using the same param name:

`q=cat&q=dog&q=fish`

Did it work like this in the past too without providing either an array of q's like `q[]` or a different body?

**Comment by natostanco** [comment]
@armantsh iirc `\r\n` still made the response make arbitrary strings relocation, the string I have come to use for like 2 months and has not afaik given me problems is `\n¶\n`, the paragraph symbol should make sure no context is shared between lines.

**Comment by geoffreyc** [comment]
Fixed in this PR:

https://github.com/Stichoza/google-translate-php/pull/88

**Comment by Stichoza** [comment]
Array translation is removed in v4.0.0. You can either implode the array with new lines as @geoffreyc suggested, or just loop translate method.
