### ISSUE TITLE
PHP Fatal error: Uncaught ErrorException: Client error: `POST http://translate.google.com/translate_a/

### ISSUE THREAD

**Issue by xaiborweb** [Stichoza/google-translate-php#73]
Hi, I'm getting this error later.
`PHP Fatal error: Uncaught ErrorException: Client error: `POST http://translate.google.com/translate_a/single?client=t&hl=en&dt=t&sl=en&tl=es&ie=UTF-8&oe=UTF-8&multires=1&otf=0&pc=1&trs=1&ssel=0&tsel=0&kc=1&t k=387179.252693` resulted in a `413 Request Entity Too Large` response:`
I think it's because the text to translate is too long.

But the big problem is that this error me for the execution of my script, I look for the way that if I receive some fatal error instead of stop the execution of the script to skip to the next and thus would not stop the execution of the script.

Any help I greatly appreciate.

**Comment by frzsombor** [comment]
As a lot of people noticed ([for example](https://productforums.google.com/forum/#!topic/translate/bmu8XS_8iTs)), a few weeks ago, Google stopped allowing long texts on Google Translate, and this is what causes the '413 Request Entity Too Large' error. As you can read on forums, and as I also can verify, Google now allows a maximum of 5000 characters. If you want to translate a longer text, you should split it to shorter parts, and translate them one-by-one.

About the uncaught exception: You should wrap your code in a try-catch block.

**Comment by ordinov** [comment]
This, for example, can be a method for splitting and translating long texts:

            $translatedText = '';
            $cutIndex = 0;
            $divider = PHP_EOL; // for example, I have a lot of new lines in my text
            
            while ( strlen($text) > $cutIndex ) {
                $startIndex = $cutIndex;
                if (strlen($text) < $cutIndex + 4999)
                    $cutIndex = strlen($text);
                else
                    $cutIndex = $startIndex + strrpos( substr($text,$startIndex,$cutIndex+4999), $divider );
                $translatedText .= $tr->translate(substr($text, $startIndex,$cutIndex)).$divider;
            }

            // return $translatedText;

**Comment by frzsombor** [comment]
@ordinov Thanks for your code, but I think this will not work with special characters, as basic string functions fail to work on them in PHP. Fortunately we have multibyte _( mb__ _)_ functions. Example:
`strlen('café'); //output: 5`
`mb_strlen('café'); //output: 4`

Also if we are talking about splitting SIMPLE, non-multibyte texts at X characters into arrays, you can use [str_split($str, $length)](http://php.net/manual/en/function.str-split.php), however this will also fail on special characters. Example: 
`str_split('café', 1); //output: array( c, a, f, �, � )`

Unfortunately there is no alternative multibyte function for str_split, but you can use this custom function below to split multibyte strings at every X characters:

```
function mb_str_split($string, $string_length = 1, $charset = 'utf-8')
{
    if (mb_strlen($string, $charset) > $string_length || !$string_length) {
        do {
            $c = mb_strlen($string, $charset);
            $parts[] = mb_substr($string, 0, $string_length, $charset);
            $string = mb_substr($string, $string_length, $c - $string_length, $charset);
        } while (!empty($string));
    } else {
        $parts = array($string);
    }
    return $parts;
}
```

``mb_str_split('mb_str_split', 1); //output: array( c, a, f, é )``
