### ISSUE TITLE
Installation woes

### ISSUE THREAD

**Issue by kklepper** [Stichoza/google-translate-php#74]
Unfortunately, I am not familiar with compose and the related technology. I tried to install according to both of your instructions

> composer require stichoza/google-translate-php

> https://github.com/Stichoza/google-translate-php/blob/master/composer.json

 but none of them worked for me.

My application is written in CodeIgniter, third-party code should reside in the subdirectory `plugins`.

This is the resulting directory layout of those 2 attempts:  

![st6](https://cloud.githubusercontent.com/assets/6130319/21362192/a02cfe66-c6e7-11e6-850d-018043cdbf8a.PNG)

The respective directory structure looks amazingly different:

![st7](https://cloud.githubusercontent.com/assets/6130319/21361690/65a88d16-c6e5-11e6-8ff1-71f7edf1f9b2.PNG)

![st8](https://cloud.githubusercontent.com/assets/6130319/21361691/6705688c-c6e5-11e6-8aa6-bd839b779128.PNG)

The beginning of my PHP module looks like

![st4](https://cloud.githubusercontent.com/assets/6130319/21362009/c918da6c-c6e6-11e6-8b91-b0d72398d57e.PNG)

As you see, I also experiment with DetectLanguage here which doesn't quite give me the results I need, which is why I finally stumbled over GoogleTranslate.  It doesn't matter if I add a backslash at the beginning of the use instruction or not.

The function in case looks like

![st5](https://cloud.githubusercontent.com/assets/6130319/21362342/3c2ba696-c6e8-11e6-8252-645350a244f1.PNG)

which results in the following error at `$tr = new TranslateClient();,` no matter which of the 2 alternatives I choose.

![st3](https://cloud.githubusercontent.com/assets/6130319/21361807/fa1c1e54-c6e5-11e6-855e-44a5e7d63248.PNG)

I verified that the proper `autoload `file is loaded in either case, so this is not the problem. The rest should be handled automatically, at least that's what I think the whole magic procedure is about.

What am I doing wrong? What is it that I don't understand? What do I have to do to make it work?

Thank you very much for any help. I tried to make it on my own, but I don't know how to phrase the problem correctly in order to find the solution.

**Comment by neo2005th** [comment]
I'm using codeigniter too, but the translate folder is in thirdparty folder, i require autoload and i´m using this only "use" that maybe you don't have in top of the controller: 
"use Stichoza\GoogleTranslate\TranslateClient;"...

Later i receive parameters from ajax script and print the result with this:
"print TranslateClient::translate($data['from_language'], $data['to_language'], $data['text']);"
