### ISSUE TITLE
cant translate if there is more than 1300 words

### ISSUE THREAD

**Issue by taner1** [Stichoza/google-translate-php#8]
It can't translate if there is more than 1300 words.

**Comment by Stichoza** [comment]
I made some changes in `v3.0.0 (pre-release)` and this is fixed already. Tested on 4200 words (30720 characters) and works perfectly.

Anyways, I won't close this issue untill stable release.

**Comment by Stichoza** [comment]
This is fixed in latest version [`v3.0.1`](https://github.com/Stichoza/google-translate-php/releases/tag/v3.0.1)
