### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by luiseffe** [Stichoza/google-translate-php#82]
Have this problem when run the composer, anyone know why?

`Problem 1
    - Can only install one of: stichoza/google-translate-php[v3.2.0, dev-master].
    - Can only install one of: stichoza/google-translate-php[v3.2.1, dev-master].
    - Can only install one of: stichoza/google-translate-php[v3.2.10, dev-master].
    - Can only install one of: stichoza/google-translate-php[v3.2.11, dev-master].
    - Can only install one of: stichoza/google-translate-php[v3.2.12, dev-master].
    - Can only install one of: stichoza/google-translate-php[v3.2.2, dev-master].
    - Can only install one of: stichoza/google-translate-php[v3.2.3, dev-master].
    - Can only install one of: stichoza/google-translate-php[v3.2.4, dev-master].
    - Can only install one of: stichoza/google-translate-php[v3.2.5, dev-master].
    - Can only install one of: stichoza/google-translate-php[v3.2.6, dev-master].
    - Can only install one of: stichoza/google-translate-php[v3.2.7, dev-master].
    - Can only install one of: stichoza/google-translate-php[v3.2.8, dev-master].
    - Can only install one of: stichoza/google-translate-php[v3.2.9, dev-master].
    - Installation request for stichoza/google-translate-php dev-master -> satisfiable by stichoza/google-translate-php[dev-master].
    - Installation request for stichoza/google-translate-php ~3.2 -> satisfiable by stichoza/google-translate-php[v3.2.0, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9].`

**Comment by albertorondelli** [comment]
There is a collision into the composer.json
The "name" must be different than the package name, try this on top:

"name": "googletranslatephp",
