### ISSUE TITLE
Filter for special words

### ISSUE THREAD

**Issue by dejurin** [Stichoza/google-translate-php#86]
When I translate in a specific subject, the translator translates the words not as needed. For example, one word has several meanings, but only one word is translated. Support the filter of words to which my translation will be called.

**Comment by Stichoza** [comment]
Is that implemented on Google Translate website?

**Comment by dejurin** [comment]
I think no. I use this

```
$words = ['word1', 'word2'];
$_words = ['replace1', 'replace2'];
str_replace($words, $_words, $tr->translate($word)),
```

**Comment by Stichoza** [comment]
So it it's no on Google Translate it won't be here. It's just a wrapper around translate.google.com
