### ISSUE TITLE
Request to better

### ISSUE THREAD

**Issue by moosavimaleki** [Stichoza/google-translate-php#89]
please public `getResponse() `function to use all result (LIKE synonym,Pronunciation,etc)
please use array for "dt" parameter in query:
`dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t`

**dt=t**
translate

**dt=bd**
full translate with synonym
in `$bodyArray[1]`

**dt=at**
other translate (in google translate page this show when click on translated word)
in `$bodyArray[5]`

**dt=ex**
example part
in `$bodyArray[13]`

**dt=ld**
i dont know
in `$bodyArray[8]`

**dt=md**
Definition part with example
in `$bodyArray[12]`

**dt=qca**
i dont know
in `$bodyArray[8]
`
**dt=rw**
read also part
in `$bodyArray[14]`

**dt=rm**
i dont know

**dt=ss**
full synonym
`in $bodyArray[11]`

**Comment by Stichoza** [comment]
Implemented in #93
