### ISSUE TITLE
Error 403 (Forbidden)!!1

### ISSUE THREAD

**Issue by aoxiang594** [Stichoza/google-translate-php#90]
http://translate.google.cn/translate_a/single 

Can anyone run it success?

**Comment by LeeThompson** [comment]
That's about where I'm at now, I got cURL to shut up and now I get 403.
It's likely because the referrer isn't set to translate.google

**Comment by LeeThompson** [comment]
I don't think the base URL is valid anymore.

`https://translate.google.com/translate_a/single`

**Comment by Stichoza** [comment]
Sorry for super-late answer. The URL is valid, working.
