### ISSUE TITLE
English to German translation issue Not utf8 encoded

### ISSUE THREAD

**Issue by nikhilnagpal123** [Stichoza/google-translate-php#94]
When translating English text to German there  are weird which are not utf8 characters, I tried utf8_encode() but that didn't work

Here is my code
 
   `use Stichoza\GoogleTranslate\TranslateClient;

   $tr = new TranslateClient('en', 'de');

   $tr->setUrlBase('http://translate.google.cn/translate_a/single');

  $description_text_de = utf8_encode($tr->translate($description_text_en));`

**Comment by Stichoza** [comment]
Can you please provide the exact text you're translating?
