### ISSUE TITLE
Api translates %s to ٪ s while creating Persian language pack

### ISSUE THREAD

**Issue by Awais-cb** [Stichoza/google-translate-php#95]
Hi guys

i have been using this API and its has been amazing.But i came across a problem which was being caused by place holder `%s` when i tried to translate a phrase with this placeholder for a Persian language this placeholder also got translated into `٪ s` after that placeholder stopped working any solution to that?

here is the sample phrase with  placeholder
`Thanks for sharing this %s`

any help would be really appreciated!

**Comment by Stichoza** [comment]
That's an issue with Google. You can just str_replace `٪ s` with `%s` after translation.

**Comment by Awais-cb** [comment]
yeah thanks @Stichoza fixed it days ago.
