### ISSUE TITLE
Update docs about configuring Guzzle

### ISSUE THREAD

**Issue by frzsombor** [Stichoza/google-translate-php#96]
The docs about configuring Guzzle on the main page is outdated, those config options are for Guzzle 5.3 ([docs](http://docs.guzzlephp.org/en/5.3/clients.html?highlight=proxy#creating-a-client)), but according to `composer.json` the project is now using Guzzle 6. And since Guzzle 6 you shouldn't use the `defaults` key in the options, but specify options directly ([docs](http://docs.guzzlephp.org/en/stable/request-options.html#proxy)), so instead of that, configure guzzle like this:

```
$tr = new TranslateClient(null, 'en', [
    'timeout' => 10,
    'proxy' => [
        'http'  => 'tcp://localhost:8125',
        'https' => 'tcp://localhost:9124'
    ],
    'headers' => [
        'User-Agent' => 'Foo/5.0 Lorem Ipsum Browser'
    ]
]);
```

**Comment by Stichoza** [comment]
Got your PR. Thanks! <3
