### ISSUE TITLE
Google response the 503 code

### ISSUE THREAD

**Issue by Nash-x9** [Stichoza/google-translate-php#98]
PHP Fatal error:  Uncaught ErrorException: Server error: `POST https://translate.google.com/translate_a/single?client=t&hl=en&dt=t&sl=zh-CN&tl=en&ie=UTF-8&oe=UTF-8&multires=1&otf=0&pc=1&trs=1&ssel=0&tsel=0&kc=1&tk=339115.204757` resulted in a `503 Service Unavailable` response:

**Comment by sakalauskas** [comment]
That's likely Google's rate limiting.

You'll need to use proxies to avoid this.

**Comment by Stichoza** [comment]
Please read the **README** file before directly copying and pasting the error code as a new issue without even reading the readme.
